name: Updates node

on:
  schedule:
    - cron: '0 0 1 1 *'
  workflow_dispatch:

jobs:
  update-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run dependency update script
        run: make deps-node-update

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update node
          branch: update-node
          title: 'Update node'
          body: |
            This pull request updates the JDK:
            - Current plugin updates
          labels: JDK
